import fs from "node:fs";
import os from "node:os";
import { pathToFileURL } from "node:url";
import { resourcesRoot } from "../../paths.js";

/**
 * The fleet inventory: which Macs exist, how to reach them, and — the part that matters —
 * which host key each one must present.
 *
 * `hosts.json` is committed, so it holds coordinates and public fingerprints only. No
 * password, no private key, no credential blob ever lands here; the identity used to reach
 * the fleet lives in ~/.yarn-runner (see ssh.ts) and is never read by this module.
 *
 * Two of the three Macs share a /24, so a host is pinned by KEY and never by address range:
 * an address that moves between machines is a routine event at a colo, and the fingerprint
 * is the only field that says "this is still the same box".
 */

/**
 * Schema tag. Read on load and refused if the major does not match, so an inventory written
 * by a newer importer fails loudly instead of being half-understood by older code.
 */
export const HOSTS_SCHEMA = "yarn-runner/hosts@1";

const SCHEMA_PREFIX = "yarn-runner/hosts@";

/** OpenSSH's fingerprint form: base64 of a SHA-256 digest, unpadded — always 43 chars. */
const FINGERPRINT = /^SHA256:[A-Za-z0-9+/]{43}$/;

/**
 * What an address and a login name are allowed to contain.
 *
 * These two fields are the only strings in the inventory that get pasted into a command line
 * a REMOTE shell expands: rsync's destination is `user@host:path`, and unlike ssh's own
 * `user@host` — which ssh consumes locally and never transmits — the whole thing crosses the
 * wire and is re-split on the far side. `rsyncDestination()` re-checks that at the point of
 * use, but a check there rejects a run that is already half set up; a check here rejects the
 * FILE, which is where the bad value entered.
 *
 * It can enter without anyone typing it: hosts.json is generated by the .rtsz importer from a
 * Royal TSX document, so the value's real provenance is a synced connection-manager file.
 *
 * No colon, which also rules out IPv6 literals. That is a real limitation and it is chosen:
 * a bracketed literal would need different handling in known_hosts tokens, in rsync's
 * destination parse and in the ControlPath, none of which is written or tested. Give the
 * machine a name.
 */
const SAFE_ADDRESS = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;
const SAFE_USER = /^[A-Za-z0-9._-]+$/;

export const DEFAULT_SSH_PORT = 22;
export const DEFAULT_VNC_PORT = 5900;

/**
 * Who is asking, from this machine's point of view.
 *
 * It selects the per-operator app profile on the far side (see `runner/profiles.ts`), so it is
 * load-bearing in a way a display name is not: sign in under one answer and submit a run under
 * another, and the run gets a different app profile than the one just signed in. Lives here,
 * shared, for exactly that reason — two modules deriving it independently is a bug waiting for
 * one of them to change.
 *
 * `YARN_OPERATOR` overrides, because the fleet's colo Macs share a console account and a
 * teammate may want their own profile without renaming their laptop login.
 */
export function defaultOperator(env: NodeJS.ProcessEnv = process.env): string {
	try {
		return env.YARN_OPERATOR?.trim() || os.userInfo().username || "unknown";
	} catch {
		return "unknown";
	}
}

export interface Endpoint {
	host: string;
	port: number;
}

export interface SshEndpoint extends Endpoint {
	user: string;
}

export interface HostEntry {
	/** Stable short name used by `--host`, run logs and the UI. Unique across the inventory. */
	name: string;
	/** Other strings that address this machine — e.g. the label an operator sees in their VNC client. */
	aliases?: string[];
	ssh: SshEndpoint;
	vnc: Endpoint;
	/**
	 * ED25519 host fingerprint, as `ssh-keyscan | ssh-keygen -lf -` prints it.
	 *
	 * `null` means the entry was imported from a source that carries no key material (see
	 * parseRtsz) and has NOT been verified. That is deliberately a distinct state from
	 * "verified": code that reaches a host must refuse a null rather than fall back to
	 * trust-on-first-use, which would accept whatever answers the address today.
	 */
	hostKey: string | null;
}

export interface Inventory {
	schema: string;
	hosts: HostEntry[];
}

/**
 * The inventory ships with the checkout, so it resolves against the resources root rather
 * than cwd — a LaunchAgent or packaged shell starts in `/` and would otherwise read nothing.
 */
export function hostsPath(): string {
	return `${resourcesRoot()}/hosts.json`;
}

/**
 * Read and fully validate the inventory.
 *
 * Every field is checked rather than cast, because the two ways this file goes wrong are
 * both silent otherwise: a hand-edit that drops a fingerprint would downgrade a host to
 * unverified, and a typo'd port would send a connection somewhere that is not the fleet.
 * Both must be a startup error, not a runtime surprise.
 */
export function loadHosts(file: string = hostsPath()): Inventory {
	let raw: unknown;
	let text: string;
	try {
		text = fs.readFileSync(file, "utf8");
	} catch (e) {
		throw new Error(`${file}: cannot read inventory (${(e as Error).message})`);
	}
	try {
		raw = JSON.parse(text);
	} catch (e) {
		throw new Error(`${file}: not valid JSON (${(e as Error).message})`);
	}

	return parseInventory(raw, file);
}

/** The validator, split out so the importer can check what it is about to write. */
export function parseInventory(raw: unknown, where = "inventory"): Inventory {
	const doc = raw as Partial<Inventory>;
	if (!doc || typeof doc !== "object" || Array.isArray(doc)) throw new Error(`${where}: expected a JSON object`);
	if (typeof doc.schema !== "string" || !doc.schema.startsWith(SCHEMA_PREFIX))
		throw new Error(`${where}: missing or unrecognised "schema" (expected ${HOSTS_SCHEMA})`);
	if (doc.schema !== HOSTS_SCHEMA) throw new Error(`${where}: schema "${doc.schema}" is not supported by this build (expected ${HOSTS_SCHEMA})`);
	if (!Array.isArray(doc.hosts)) throw new Error(`${where}: "hosts" must be an array`);

	const seen = new Set<string>();
	const hosts = doc.hosts.map((h, i) => {
		const entry = parseEntry(h, `${where}: hosts[${i}]`);
		// A duplicate name makes `--host mac2` ambiguous, and the ambiguity would resolve
		// differently depending on array order. Cheaper to refuse the file.
		const key = entry.name.toLowerCase();
		if (seen.has(key)) throw new Error(`${where}: duplicate host name "${entry.name}"`);
		seen.add(key);

		return entry;
	});

	return { schema: doc.schema, hosts };
}

function parseEntry(raw: unknown, where: string): HostEntry {
	const h = raw as Partial<HostEntry>;
	if (!h || typeof h !== "object" || Array.isArray(h)) throw new Error(`${where}: expected an object`);
	if (typeof h.name !== "string" || !h.name.trim()) throw new Error(`${where}: "name" must be a non-empty string`);
	if (h.aliases !== undefined && (!Array.isArray(h.aliases) || h.aliases.some((a) => typeof a !== "string")))
		throw new Error(`${where}: "aliases" must be an array of strings`);
	if (h.hostKey !== null && (typeof h.hostKey !== "string" || !FINGERPRINT.test(h.hostKey)))
		throw new Error(`${where}: "hostKey" must be null or a SHA256:… fingerprint, got ${JSON.stringify(h.hostKey)}`);

	const ssh = parseEndpoint(h.ssh, `${where}.ssh`);
	const vnc = parseEndpoint(h.vnc, `${where}.vnc`);
	const user = (h.ssh as SshEndpoint | undefined)?.user;
	if (typeof user !== "string" || !user.trim()) throw new Error(`${where}.ssh: "user" must be a non-empty string`);
	if (!SAFE_USER.test(user.trim()))
		throw new Error(`${where}.ssh: "user" ${JSON.stringify(user)} contains characters a remote shell would interpret`);

	return {
		name: h.name.trim(),
		...(h.aliases?.length ? { aliases: h.aliases } : {}),
		ssh: { ...ssh, user: user.trim() },
		vnc,
		hostKey: h.hostKey,
	};
}

function parseEndpoint(raw: unknown, where: string): Endpoint {
	const e = raw as Partial<Endpoint>;
	if (!e || typeof e !== "object") throw new Error(`${where}: expected an object`);
	if (typeof e.host !== "string" || !e.host.trim()) throw new Error(`${where}: "host" must be a non-empty string`);
	if (!SAFE_ADDRESS.test(e.host.trim()))
		throw new Error(`${where}: "host" ${JSON.stringify(e.host)} is not a hostname or IPv4 address (no IPv6 literals — give the machine a name)`);
	if (!Number.isInteger(e.port) || (e.port as number) < 1 || (e.port as number) > 65535)
		throw new Error(`${where}: "port" must be an integer 1-65535, got ${JSON.stringify(e.port)}`);

	return { host: e.host.trim(), port: e.port as number };
}

/**
 * Find a host by name, alias, or literal address.
 *
 * Addresses are accepted because an operator reading a VNC window title or a colo ticket has
 * the IP in front of them and not the short name; the lookup is the same either way.
 */
export function resolveHost(nameOrAlias: string, inv: Inventory = loadHosts()): HostEntry {
	const want = nameOrAlias.trim().toLowerCase();
	const match = inv.hosts.find(
		(h) =>
			h.name.toLowerCase() === want ||
			h.ssh.host.toLowerCase() === want ||
			h.vnc.host.toLowerCase() === want ||
			(h.aliases ?? []).some((a) => a.toLowerCase() === want),
	);
	if (!match) throw new Error(`unknown host "${nameOrAlias}" — inventory has ${inv.hosts.map((h) => h.name).join(", ") || "no hosts"}`);

	return match;
}

/** One `<RoyalVNCConnection>` from a Royal TSX document. Names and VNC coordinates only. */
export interface RtszEntry {
	name: string;
	host: string;
	vncPort: number;
}

/**
 * Matches a connection element and captures its body. `\b[^>]*` tolerates attributes; the
 * lazy body stops at the first close tag, which is correct here because these elements do
 * not nest.
 */
const VNC_BLOCK = /<RoyalVNCConnection\b[^>]*>([\s\S]*?)<\/RoyalVNCConnection>/g;

/**
 * Parse a Royal TSX `.rtsz` workspace and return its VNC connections.
 *
 * No XML dependency: the document is machine-written, flat, and we want exactly three of its
 * ~40 child elements. A scan for those three is smaller than the parser it would replace, is
 * indifferent to child order and to children we have never seen, and — the reason it is
 * preferable rather than merely sufficient — it CANNOT accidentally surface a field we did
 * not ask for. These documents carry `<CredentialPassword>` and `<Password>` blobs; nothing
 * below reads them, and no future refactor of a generic parse-then-map can start to.
 *
 * The format also does not carry what SSH needs: no SSH port, no username, and no host key.
 * Imported entries are therefore left `hostKey: null` by importHosts rather than defaulted
 * to something that looks pinned.
 */
export function parseRtsz(xml: string): RtszEntry[] {
	// UTF-8 BOM. Royal TSX writes one; left in place it becomes part of the first tag and
	// every match silently fails, which reads as "the document has no connections".
	const doc = xml.replace(/^\uFEFF/, "");

	const out: RtszEntry[] = [];
	for (const [, body] of doc.matchAll(VNC_BLOCK)) {
		const host = childText(body, "URI");
		if (!host) continue; // a template row with no address is not a machine

		const port = Number(childText(body, "Port"));
		out.push({
			name: childText(body, "Name") || host,
			host,
			vncPort: Number.isInteger(port) && port > 0 ? port : DEFAULT_VNC_PORT,
		});
	}

	return out;
}

/** First `<tag>…</tag>` in a block. Self-closing (`<Name />`) yields "" — the same as absent. */
function childText(body: string, tag: string): string {
	const m = body.match(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`));

	return m ? decodeEntities(m[1]).trim() : "";
}

function decodeEntities(s: string): string {
	return s
		.replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
		.replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
		.replace(/&lt;/g, "<")
		.replace(/&gt;/g, ">")
		.replace(/&quot;/g, '"')
		.replace(/&apos;/g, "'")
		// Ampersand last, so "&amp;lt;" decodes to the literal "&lt;" and not to "<".
		.replace(/&amp;/g, "&");
}

export interface ImportResult {
	inventory: Inventory;
	added: string[];
	skipped: { name: string; reason: string }[];
}

/**
 * Merge parsed connections into an inventory, additively.
 *
 * Additive is the whole contract: an existing entry is never rewritten, and in particular a
 * pinned `hostKey` is never dropped by re-importing the document that could not have
 * supplied one. An import can only ever grow the fleet; removing a host stays a deliberate
 * hand edit.
 *
 * New entries carry `hostKey: null` and are unusable until someone pins them — that is the
 * intended friction, since the alternative is an entry that connects on first sight.
 */
export function importHosts(xml: string, inv: Inventory, opts: { user: string; sshPort?: number }): ImportResult {
	const sshPort = opts.sshPort ?? DEFAULT_SSH_PORT;
	const hosts = [...inv.hosts];
	const added: string[] = [];
	const skipped: { name: string; reason: string }[] = [];

	for (const entry of parseRtsz(xml)) {
		const want = entry.host.toLowerCase();
		const name = entry.name.toLowerCase();
		const existing = hosts.find(
			(h) =>
				h.ssh.host.toLowerCase() === want ||
				h.vnc.host.toLowerCase() === want ||
				h.name.toLowerCase() === name ||
				(h.aliases ?? []).some((a) => a.toLowerCase() === name),
		);
		if (existing) {
			skipped.push({
				name: entry.name,
				reason: existing.hostKey ? `already in inventory as "${existing.name}" with a pinned host key` : `already in inventory as "${existing.name}"`,
			});
			continue;
		}

		hosts.push({
			name: entry.name,
			ssh: { host: entry.host, port: sshPort, user: opts.user },
			vnc: { host: entry.host, port: entry.vncPort },
			hostKey: null,
		});
		added.push(entry.name);
	}

	return { inventory: { schema: HOSTS_SCHEMA, hosts }, added, skipped };
}

/**
 * Importer entry point: read a `.rtsz`, merge into `hosts.json`, write it back.
 *
 * The inventory is re-validated before it is written, so a merge can never leave behind a
 * file that the next loadHosts() refuses.
 */
export function importHostsFile(rtszPath: string, opts: { user: string; sshPort?: number; hostsFile?: string }): ImportResult {
	const file = opts.hostsFile ?? hostsPath();
	const inv = fs.existsSync(file) ? loadHosts(file) : { schema: HOSTS_SCHEMA, hosts: [] };
	const result = importHosts(fs.readFileSync(rtszPath, "utf8"), inv, opts);
	parseInventory(result.inventory, file);
	fs.writeFileSync(file, `${JSON.stringify(result.inventory, null, 2)}\n`);

	return result;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
	const [rtsz, user] = process.argv.slice(2);
	if (!rtsz || !user) {
		console.error('usage: tsx src/fleet/remote/hosts.ts <workspace.rtsz> <ssh-user>   # merges into hosts.json, never overwrites');
		process.exit(2);
	}
	const result = importHostsFile(rtsz, { user });
	for (const name of result.added) console.log(`+ ${name} (needs a host key: run ssh-keyscan and paste the fingerprint into hosts.json)`);
	for (const s of result.skipped) console.log(`  skipped ${s.name} — ${s.reason}`);
	console.log(`${result.added.length} added, ${result.skipped.length} skipped, ${result.inventory.hosts.length} hosts total`);
}
